export const PREGUNTAS_TRIVIA = [
  { pregunta: '¿Cuál es el planeta más grande del sistema solar?', respuesta: 'jupiter' },
  { pregunta: '¿En qué país se encuentra la Torre Eiffel?', respuesta: 'francia' },
  { pregunta: '¿Cuántos continentes hay en el mundo?', respuesta: '7' },
  { pregunta: '¿Cuál es el océano más grande del mundo?', respuesta: 'pacifico' },
  { pregunta: '¿Qué gas respiramos principalmente para vivir?', respuesta: 'oxigeno' },
  { pregunta: '¿Cuál es la capital de Perú?', respuesta: 'lima' },
  { pregunta: '¿Cuántos lados tiene un hexágono?', respuesta: '6' },
  { pregunta: '¿Qué animal es conocido como el rey de la selva?', respuesta: 'leon' },
  { pregunta: '¿En qué país se originó el karaoke?', respuesta: 'japon' },
  { pregunta: '¿Cuál es el único metal líquido a temperatura ambiente?', respuesta: 'mercurio' },
  { pregunta: '¿Cuántos huesos tiene el cuerpo humano adulto?', respuesta: '206' },
  { pregunta: '¿Cuál es el río más largo del mundo?', respuesta: 'amazonas' },
  { pregunta: '¿Qué instrumento se usa para medir la temperatura?', respuesta: 'termometro' },
  { pregunta: '¿Cuántas patas tiene una araña?', respuesta: '8' },
  { pregunta: '¿Cuál es la moneda oficial de Japón?', respuesta: 'yen' },
  { pregunta: '¿Cuál es el país más grande del mundo por superficie?', respuesta: 'rusia' },
  { pregunta: '¿Quién pintó la Mona Lisa?', respuesta: 'leonardo da vinci' },
  { pregunta: '¿Cuál es el elemento químico con el símbolo H?', respuesta: 'hidrogeno' },
  { pregunta: '¿En qué año terminó la Segunda Guerra Mundial?', respuesta: '1945' },
  { pregunta: '¿Cuál es la capital de Italia?', respuesta: 'roma' },
  { pregunta: '¿Qué tipo de animal es una ballena?', respuesta: 'mamifero' },
  { pregunta: '¿Cuál es el metal más caro del mundo?', respuesta: 'rodio' },
  { pregunta: '¿Cuántos minutos tiene una hora?', respuesta: '60' },
  { pregunta: '¿Cuál es el idioma más hablado en el mundo?', respuesta: 'chino mandarin' },
  { pregunta: '¿Quién escribió "Don Quijote de la Mancha"?', respuesta: 'miguel de cervantes' },
  { pregunta: '¿Cuál es la montaña más alta del mundo?', respuesta: 'everest' },
  { pregunta: '¿Qué órgano del cuerpo bombea sangre?', respuesta: 'corazon' },
  { pregunta: '¿Cuál es la capital de España?', respuesta: 'madrid' },
  { pregunta: '¿En qué país se encuentra la Gran Muralla?', respuesta: 'china' },
  { pregunta: '¿Cuál es el color de la esmeralda?', respuesta: 'verde' },
  { pregunta: '¿Cuántos días tiene un año bisiesto?', respuesta: '366' },
  { pregunta: '¿Cuál es la capital de Argentina?', respuesta: 'buenos aires' },
  { pregunta: '¿Qué animal pone los huevos más grandes?', respuesta: 'avestruz' },
  { pregunta: '¿Cuál es el planeta más cercano al Sol?', respuesta: 'mercurio' },
  { pregunta: '¿Quién descubrió América?', respuesta: 'cristobal colon' },
  { pregunta: '¿Cuál es el deporte más popular del mundo?', respuesta: 'futbol' },
  { pregunta: '¿Qué gas absorben las plantas?', respuesta: 'dioxido de carbono' },
  { pregunta: '¿Cuál es la capital de México?', respuesta: 'ciudad de mexico' },
  { pregunta: '¿Cuántos años tiene un siglo?', respuesta: '100' },
  { pregunta: '¿Cuál es el animal terrestre más rápido?', respuesta: 'guepardo' },
  { pregunta: '¿En qué continente está Egipto?', respuesta: 'africa' },
  { pregunta: '¿Cuál es la capital de Francia?', respuesta: 'paris' },
  { pregunta: '¿Qué satélite natural tiene la Tierra?', respuesta: 'luna' },
  { pregunta: '¿Quién fue el primer hombre en la Luna?', respuesta: 'neil armstrong' },
  { pregunta: '¿Cuál es el tercer planeta del sistema solar?', respuesta: 'tierra' },
  { pregunta: '¿Cuál es la capital de Colombia?', respuesta: 'bogota' },
  { pregunta: '¿Qué animal es el mejor amigo del hombre?', respuesta: 'perro' },
  { pregunta: '¿Cuántos colores tiene el arcoíris?', respuesta: '7' },
  { pregunta: '¿Cuál es el hueso más largo del cuerpo?', respuesta: 'femur' },
  { pregunta: '¿En qué año comenzó la Primera Guerra Mundial?', respuesta: '1914' },
  { pregunta: '¿Cuál es la capital de Alemania?', respuesta: 'berlin' },
  { pregunta: '¿Qué fruta es roja y tiene semillas por fuera?', respuesta: 'fresa' },
  { pregunta: '¿Cuál es el país más pequeño del mundo?', respuesta: 'vaticano' },
  { pregunta: '¿Cuántos segundos tiene un minuto?', respuesta: '60' },
  { pregunta: '¿Cuál es la capital de Chile?', respuesta: 'santiago' },
  { pregunta: '¿Qué metal atrae un imán?', respuesta: 'hierro' },
  { pregunta: '¿Cuál es el desierto más caluroso del mundo?', respuesta: 'sahara' },
  { pregunta: '¿Quién escribió "Cien años de soledad"?', respuesta: 'gabriel garcia marquez' },
  { pregunta: '¿Cuál es la capital de Brasil?', respuesta: 'brasilia' },
  { pregunta: '¿Qué animal vive más tiempo?', respuesta: 'tortuga' },
  { pregunta: '¿Cuántos meses tienen 31 días?', respuesta: '7' },
  { pregunta: '¿Cuál es el nombre de la galaxia donde vivimos?', respuesta: 'via lactea' },
  { pregunta: '¿Quién es el autor de Hamlet?', respuesta: 'william shakespeare' },
  { pregunta: '¿Cuál es la capital de Rusia?', respuesta: 'moscu' },
  { pregunta: '¿Qué parte del cuerpo tiene más bacterias?', respuesta: 'boca' },
  { pregunta: '¿Cuál es el ave que no vuela y vive en el frío?', respuesta: 'pinguino' },
  { pregunta: '¿En qué país se inventó la pizza?', respuesta: 'italía' },
  { pregunta: '¿Cuál es la capital de Portugal?', respuesta: 'lisboa' },
  { pregunta: '¿Cuántos corazones tiene un pulpo?', respuesta: '3' },
  { pregunta: '¿Cuál es el planeta conocido como el planeta rojo?', respuesta: 'marte' },
  { pregunta: '¿Quién inventó la bombilla?', respuesta: 'thomas edison' },
  { pregunta: '¿Cuál es la capital de Estados Unidos?', respuesta: 'washington dc' },
  { pregunta: '¿Qué animal tiene la lengua más larga?', respuesta: 'camaleon' },
  { pregunta: '¿Cuántos planetas hay en el sistema solar?', respuesta: '8' },
  { pregunta: '¿Cuál es el animal más pesado del mundo?', respuesta: 'ballena azul' },
  { pregunta: '¿En qué país se encuentran las pirámides de Giza?', respuesta: 'egipto' },
  { pregunta: '¿Cuál es la capital de Canadá?', respuesta: 'ottawa' },
  { pregunta: '¿Qué gas protege a la Tierra de los rayos UV?', respuesta: 'ozono' },
  { pregunta: '¿Cuál es el instrumento musical más antiguo?', respuesta: 'flauta' },
  { pregunta: '¿Cuántos litros de agua debe beber un adulto al día?', respuesta: '2' },
  { pregunta: '¿Cuál es la capital de China?', respuesta: 'pekin' },
  { pregunta: '¿Qué animal puede dormir tres años?', respuesta: 'caracol' },
  { pregunta: '¿Cuál es el elemento químico con el símbolo Au?', respuesta: 'oro' },
  { pregunta: '¿Quién fundó Microsoft?', respuesta: 'bill gates' },
  { pregunta: '¿Cuál es la capital de Australia?', respuesta: 'canberra' },
  { pregunta: '¿Qué animal es el símbolo de la paz?', respuesta: 'paloma' },
  { pregunta: '¿Cuántas teclas tiene un piano estándar?', respuesta: '88' },
  { pregunta: '¿Cuál es el país con más habitantes del mundo?', respuesta: 'india' },
  { pregunta: '¿En qué año cayó el muro de Berlín?', respuesta: '1989' },
  { pregunta: '¿Cuál es la capital de Japón?', respuesta: 'tokio' },
  { pregunta: '¿Qué animal no puede saltar?', respuesta: 'elefante' },
  { pregunta: '¿Cuál es el océano que baña las costas de Europa?', respuesta: 'atlantico' },
  { pregunta: '¿Quién pintó la Capilla Sixtina?', respuesta: 'miguel angel' },
  { pregunta: '¿Cuál es la capital de Grecia?', respuesta: 'atenas' },
  { pregunta: '¿Qué órgano filtra la sangre?', respuesta: 'riñon' },
  { pregunta: '¿Cuál es la flor nacional de Japón?', respuesta: 'cerezo' },
  { pregunta: '¿En qué ciudad se encuentra la Estatua de la Libertad?', respuesta: 'nueva york' },
  { pregunta: '¿Cuál es la capital de Egipto?', respuesta: 'el cairo' },
  { pregunta: '¿Qué animal tiene las huellas dactilares parecidas a los humanos?', respuesta: 'koala' },
  { pregunta: '¿Cuál es el metal que mejor conduce la electricidad?', respuesta: 'plata' },
  { pregunta: '¿Quién escribió "La Odisea"?', respuesta: 'homero' },
  { pregunta: '¿Cuál es la capital de Turquía?', respuesta: 'ankara' },
  { pregunta: '¿Qué animal es el más inteligente después del humano?', respuesta: 'delfin' },
  { pregunta: '¿Cuántos dientes tiene un adulto humano?', respuesta: '32' },
  { pregunta: '¿Cuál es el país más visitado del mundo?', respuesta: 'francia' },
  { pregunta: '¿En qué año llegó el hombre a la Luna?', respuesta: '1969' },
  { pregunta: '¿Cuál es la capital de Tailandia?', respuesta: 'bangkok' },
  { pregunta: '¿Qué animal cambia de color según su entorno?', respuesta: 'camaleon' },
  { pregunta: '¿Cuál es el lago más profundo del mundo?', respuesta: 'baikal' },
  { pregunta: '¿Quién desarrolló la teoría de la relatividad?', respuesta: 'albert einstein' },
  { pregunta: '¿Cuál es la capital de Cuba?', respuesta: 'la habana' },
  { pregunta: '¿Qué gas es el más abundante en la atmósfera?', respuesta: 'nitrogeno' },
  { pregunta: '¿Cuál es el ave más pequeña del mundo?', respuesta: 'colibri' },
  { pregunta: '¿En qué país está el Machu Picchu?', respuesta: 'peru' },
  { pregunta: '¿Cuál es la capital de Suiza?', respuesta: 'berna' },
  { pregunta: '¿Qué animal no tiene cerebro ni corazón?', respuesta: 'medusa' },
  { pregunta: '¿Cuál es el país con más islas del mundo?', respuesta: 'suecia' },
  { pregunta: '¿Quién inventó el teléfono?', respuesta: 'alexander graham bell' },
  { pregunta: '¿Cuál es la capital de Marruecos?', respuesta: 'rabat' },
  { pregunta: '¿Qué animal tiene la mordida más fuerte?', respuesta: 'cocodrilo' },
  { pregunta: '¿Cuántos jugadores hay en un equipo de baloncesto?', respuesta: '5' },
  { pregunta: '¿Cuál es el país que produce más café en el mundo?', respuesta: 'brasil' },
  { pregunta: '¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos?', respuesta: 'atenas' },
  { pregunta: '¿Cuál es la capital de Holanda?', respuesta: 'amsterdam' },
  { pregunta: '¿Qué animal puede ver en la oscuridad total?', respuesta: 'buho' },
  { pregunta: '¿Cuál es el mineral más duro de la naturaleza?', respuesta: 'diamante' },
  { pregunta: '¿Cuál es el hueso más pequeño del cuerpo?', respuesta: 'estribo' },
  { pregunta: '¿En qué país nació Albert Einstein?', respuesta: 'alemania' },
  { pregunta: '¿Cuál es el animal más rápido del océano?', respuesta: 'pez vela' },
  { pregunta: '¿Cuántas válvulas tiene el corazón humano?', respuesta: '4' },
  { pregunta: '¿Cuál es la capital de Corea del Sur?', respuesta: 'seul' },
  { pregunta: '¿Qué gas exhalamos al respirar?', respuesta: 'dioxido de carbono' },
  { pregunta: '¿Cuál es el mamífero más grande de la tierra?', respuesta: 'elefante africano' },
  { pregunta: '¿Quién pintó El Grito?', respuesta: 'edvard munch' },
  { pregunta: '¿Cuál es el país con más pirámides del mundo?', respuesta: 'sudan' },
  { pregunta: '¿En qué año se hundió el Titanic?', respuesta: '1912' },
  { pregunta: '¿Cuál es la capital de Noruega?', respuesta: 'oslo' },
  { pregunta: '¿Qué animal no tiene cuerdas vocales?', respuesta: 'jirafa' },
  { pregunta: '¿Cuál es el metal más abundante en la corteza terrestre?', respuesta: 'aluminio' },
  { pregunta: '¿Cuántos estómagos tiene una vaca?', respuesta: '4' },
  { pregunta: '¿Cuál es la capital de Austria?', respuesta: 'viena' },
  { pregunta: '¿Quién escribió El Principito?', respuesta: 'antoine de saint-exupery' },
  { pregunta: '¿Cuál es el país más joven del mundo?', respuesta: 'sudan del sur' },
  { pregunta: '¿Qué planeta tiene los anillos más visibles?', respuesta: 'saturno' },
  { pregunta: '¿Cuál es la capital de Suecia?', respuesta: 'estocolmo' },
  { pregunta: '¿Qué animal tiene tres párpados?', respuesta: 'camello' },
  { pregunta: '¿Cuál es el río más largo de Europa?', respuesta: 'volga' },
  { pregunta: '¿Quién descubrió la penicilina?', respuesta: 'alexander fleming' },
  { pregunta: '¿Cuál es la capital de Bélgica?', respuesta: 'bruselas' },
  { pregunta: '¿Qué animal es el único mamífero que vuela?', respuesta: 'murcielago' },
  { pregunta: '¿Cuántos dientes de leche tienen los niños?', respuesta: '20' },
  { pregunta: '¿Cuál es el país más grande de África?', respuesta: 'argelia' },
  { pregunta: '¿En qué año comenzó la Revolución Francesa?', respuesta: '1789' },
  { pregunta: '¿Cuál es la capital de Dinamarca?', respuesta: 'copenhague' },
  { pregunta: '¿Qué animal tiene la gestación más larga?', respuesta: 'elefante' },
  { pregunta: '¿Cuál es el componente principal del sol?', respuesta: 'hidrogeno' },
  { pregunta: '¿Quién escribió La metamorfosis?', respuesta: 'franz kafka' },
  { pregunta: '¿Cuál es la capital de Finlandia?', respuesta: 'helsinki' },
  { pregunta: '¿Qué animal puede regenerar sus extremidades?', respuesta: 'estrella de mar' },
  { pregunta: '¿Cuál es el país más poblado de África?', respuesta: 'nigeria' },
  { pregunta: '¿Quién inventó la radio?', respuesta: 'guglielmo marconi' },
  { pregunta: '¿Cuál es la capital de Irlanda?', respuesta: 'dublin' },
  { pregunta: '¿Qué animal tiene la presión arterial más alta?', respuesta: 'jirafa' },
  { pregunta: '¿Cuántos jugadores hay en un equipo de voleibol?', respuesta: '6' },
  { pregunta: '¿Cuál es el país más montañoso de Europa?', respuesta: 'suiza' },
  { pregunta: '¿En qué ciudad nació la democracia?', respuesta: 'atenas' },
  { pregunta: '¿Cuál es la capital de Hungría?', respuesta: 'budapest' },
  { pregunta: '¿Qué animal tiene la visión más aguda?', respuesta: 'aguila' },
  { pregunta: '¿Cuál es el metal que se usa para fabricar latas?', respuesta: 'aluminio' },
  { pregunta: '¿Quién pintó Las Meninas?', respuesta: 'diego velazquez' },
  { pregunta: '¿Cuál es la capital de Polonia?', respuesta: 'varsovia' },
  { pregunta: '¿Qué animal es el pariente más cercano del humano?', respuesta: 'bonobo' },
  { pregunta: '¿Cuántas cuerdas tiene una guitarra estándar?', respuesta: '6' },
  { pregunta: '¿Cuál es el país que tiene forma de bota?', respuesta: 'italia' },
  { pregunta: '¿En qué año se inventó la World Wide Web?', respuesta: '1989' },
  { pregunta: '¿Cuál es la capital de República Checa?', respuesta: 'praga' },
  { pregunta: '¿Qué animal es capaz de volar hacia atrás?', respuesta: 'colibri' },
  { pregunta: '¿Cuál es el punto más bajo de la tierra?', respuesta: 'mar muerto' },
  { pregunta: '¿Quién escribió Romeo y Julieta?', respuesta: 'william shakespeare' },
  { pregunta: '¿Cuál es la capital de Rumanía?', respuesta: 'bucarest' },
  { pregunta: '¿Qué animal es el depredador más grande del Ártico?', respuesta: 'oso polar' },
  { pregunta: '¿Cuántos elementos hay en la tabla periódica?', respuesta: '118' },
  { pregunta: '¿Cuál es el país con más husos horarios?', respuesta: 'francia' },
  { pregunta: '¿Quién inventó la televisión?', respuesta: 'john logie baird' },
  { pregunta: '¿Cuál es la capital de Ucrania?', respuesta: 'kiev' },
  { pregunta: '¿Qué animal es el único que no puede retroceder?', respuesta: 'canguro' },
  { pregunta: '¿Cuál es el país que tiene más volcanes activos?', respuesta: 'indonesia' },
  { pregunta: '¿En qué año terminó la Guerra Fría?', respuesta: '1991' },
  { pregunta: '¿Cuál es la capital de Nueva Zelanda?', respuesta: 'wellington' },
  { pregunta: '¿Qué animal tiene el corazón más grande?', respuesta: 'ballena azul' },
  { pregunta: '¿Cuál es el río más largo de Asia?', respuesta: 'yangtse' },
  { pregunta: '¿Quién escribió Odisea en el espacio?', respuesta: 'arthur c clarke' },
  { pregunta: '¿Cuál es la capital de Vietnam?', respuesta: 'hanoi' },
  { pregunta: '¿Qué animal tiene el cerebro más grande?', respuesta: 'cachalote' },
  { pregunta: '¿Cuántas estrellas tiene la bandera de Estados Unidos?', respuesta: '50' },
  { pregunta: '¿Cuál es el país con más lagos del mundo?', respuesta: 'canada' },
  { pregunta: '¿En qué país se inventó el ajedrez?', respuesta: 'india' },
  { pregunta: '¿Cuál es la capital de Indonesia?', respuesta: 'yakarta' },
  { pregunta: '¿Qué animal tiene el cuello más largo?', respuesta: 'jirafa' },
  { pregunta: '¿Cuál es el planeta con más lunas?', respuesta: 'saturno' },
  { pregunta: '¿Quién pintó la Guernica?', respuesta: 'pablo picasso' },
  { pregunta: '¿Cuál es la capital de Sudáfrica?', respuesta: 'pretoria' },
  { pregunta: '¿Qué animal es el mamífero más rápido del agua?', respuesta: 'orca' },
  { pregunta: '¿Cuántos huesos tiene un tiburón?', respuesta: '0' },
  { pregunta: '¿Cuál es el país más biodiverso del mundo?', respuesta: 'brasil' },
  { pregunta: '¿En qué año se lanzó el primer iPhone?', respuesta: '2007' },
  { pregunta: '¿Cuál es la capital de Islandia?', respuesta: 'reikiavik' },
  { pregunta: '¿Qué animal es el símbolo de Australia?', respuesta: 'canguro' },
  { pregunta: '¿Cuál es el metal más denso?', respuesta: 'osmio' },
]

export const PALABRAS_AHORCADO = [
  'javascript', 'termux', 'whatsapp', 'programacion', 'computadora',
  'internet', 'servidor', 'mensaje', 'usuario', 'economia',
  'aventura', 'mariposa', 'universo', 'biblioteca', 'chocolate',
]

export function normalizarTexto(texto) {
  return texto
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()
}

const triviasActivas = new Map()
const ahorcadosActivos = new Map()

export function obtenerTriviaActiva(chatId) {
  return triviasActivas.get(chatId)
}

export function iniciarTrivia(chatId, datos) {
  triviasActivas.set(chatId, datos)
}

export function finalizarTrivia(chatId) {
  const datos = triviasActivas.get(chatId)
  if (datos?.timeoutId) clearTimeout(datos.timeoutId)
  triviasActivas.delete(chatId)
}

export function obtenerAhorcadoActivo(chatId) {
  return ahorcadosActivos.get(chatId)
}

export function iniciarAhorcado(chatId, datos) {
  ahorcadosActivos.set(chatId, datos)
}

export function finalizarAhorcado(chatId) {
  const datos = ahorcadosActivos.get(chatId)
  if (datos?.timeoutId) clearTimeout(datos.timeoutId)
  ahorcadosActivos.delete(chatId)
}

export function dibujarAhorcado(intentosRestantes) {
  const etapas = [
    '💀 Perdiste',
    '🪦\n😵',
    '🪦\n😰',
    '🪦\n😨',
    '🪦\n😟',
    '🪦\n🙂',
    '🪦\n😄',
  ]
  return etapas[Math.min(intentosRestantes, etapas.length - 1)]
}
